data:
  inputs:
    csv_data_information_file: "../resources/data/data_information.csv"
    json_inputs_file: "../resources/data/parameters.json"
  outputs:
    json_outputs_file: "../resources/data/outputs.json"
    excel_outputs_file: "../resources/data/data.xlsx"

models:
  climate:
    climate_model_data_file: default

  fleet:
    aircraft_inventory_model_data_file: default
    fleet_model_data_file: default

  energy:
    energy_carriers_model_data_file: default
    resources_model_data_file: default
    processes_model_data_file: default

  standards:
    - models_traffic
    - models_efficiency_bottom_up
    - models_energy_without_fuel_effect
    - models_offset
    - models_emissions
    - models_sustainability
    - models_energy_cost
    - models_operation_cost_bottom_up
